name: challenge chap2

on: push

jobs:
    job1:
        name: First Job
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo to runner (job 1)
              uses: actions/checkout@v4
            - name: Print date (Ubuntu)
              run: date
    job2:
        name: Second Job
        runs-on: windows-latest
        steps:
            - name: Checkout repo to runner (job 2)
              uses: actions/checkout@v4
            - name: Print date (Windows)
              run: Get-Date
    job3:
        name: Third job
        runs-on: macos-latest
        steps:
            - name: Checkout repo to runner (job 3)
              uses: actions/checkout@v4
            - name: Print date (Mac-OS)
              run: date -I
    job4:
        name: Fourth job
        needs: [job1, job2, job3]
        runs-on: windows-latest
        steps:
            - name: Checkout repo to runner (job 4)
              uses: actions/checkout@v4
            - name: Print date (Windows, again)
              run: echo %date%